// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Primera.Context;

#nullable disable

namespace Primera.Migrations
{
    [DbContext(typeof(PrimeraContext))]
    partial class PrimeraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Primera.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Conceded")
                        .HasColumnType("int");

                    b.Property<int>("Draw")
                        .HasColumnType("int");

                    b.Property<int>("Lose")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scored")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Madrid",
                            Conceded = 0,
                            Draw = 0,
                            Lose = 0,
                            Name = "Real Madrid",
                            Scored = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            City = "Barcelona",
                            Conceded = 0,
                            Draw = 0,
                            Lose = 0,
                            Name = "Barcelona",
                            Scored = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            City = "Madrid",
                            Conceded = 0,
                            Draw = 0,
                            Lose = 0,
                            Name = "Atletico Madrid",
                            Scored = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            City = "Valencia",
                            Conceded = 0,
                            Draw = 0,
                            Lose = 0,
                            Name = "Valencia",
                            Scored = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            City = "Sevilla",
                            Conceded = 0,
                            Draw = 0,
                            Lose = 0,
                            Name = "Sevilla",
                            Scored = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            City = "San Sebastian",
                            Conceded = 0,
                            Draw = 0,
                            Lose = 0,
                            Name = "Real Sociedad",
                            Scored = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            City = "Villarreal",
                            Conceded = 0,
                            Draw = 0,
                            Lose = 0,
                            Name = "Villarreal",
                            Scored = 0,
                            Wins = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
